import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-full bg-linear-to-r from-(--p-l-background-color) to-(--p-d-background-color)
      font-['Montserrat',sans-serif]">
        
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Suspense>
            {children}
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
